image: debian:12

stages:
  - build
  - upload
  - release

variables:
  ARTIFACT_URL: "/builds/${CI_PROJECT_PATH}/build/cpack"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nebula-atom/${CI_COMMIT_TAG}"

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y
      make
      binutils
      g++
      git
      cmake
      libssl-dev
      libpoco-dev
      libmariadb-dev
      libyaml-cpp-dev
  script:
    - mkdir build && cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=release && cmake --build .
    - cmake --build . --target install
    - cpack --config CPackSourceConfig.cmake && cpack --config CPackConfig.cmake
  artifacts:
    paths:
      - build/cpack/nebula-atom-*-Linux.deb

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "master" == "dev"
  script:
    - |
      TAG=${CI_COMMIT_TAG} && VERSION=${TAG:1} && export LINUX_DEB_FILE="nebula-atom-${VERSION}-Linux.deb" && 
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${ARTIFACT_URL}/${LINUX_DEB_FILE} ${PACKAGE_REGISTRY_URL}/${LINUX_DEB_FILE}

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "master" == "dev"
  script:
    - |
      TAG=${CI_COMMIT_TAG} && VERSION=${TAG:1} && export LINUX_DEB_FILE="nebula-atom-${VERSION}-Linux.deb" && 
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${LINUX_DEB_FILE}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${LINUX_DEB_FILE}\"}"

