image: debian:12

stages:
  - build
#  - release

#variables:
#  VAR_LATEST: $CI_REGISTRY_IMAGE/nebula_atom_image:latest
#  VAR_TAG: $CI_REGISTRY_IMAGE/nebula_atom_image:$CI_COMMIT_TAG

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y
      make
      binutils
      g++
      git
      cmake
      libssl-dev
      libpoco-dev
      libmariadb-dev
      libyaml-cpp-dev
  script:
    - mkdir build && cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=release && cmake --build .
    - cmake --build . --target install

