
name: CMake System for Nebula Atom

on:
  push

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:12

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y make binutils g++ git cmake libssl-dev
        apt-get install -y libpoco-dev libmariadb-dev libyaml-cpp-dev
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build .

    - name: Build
      working-directory: build
      run: |
        cmake --build . --target install

    - name: CPack
      working-directory: build
      run: |
        cpack --config CPackSourceConfig.cmake
        cpack --config CPackConfig.cmake

    - name: Test
      working-directory: build
      run: src/example/helloworld
